nelmio_cors:
        defaults:
            allow_credentials: true
            allow_origin: []
            allow_headers: ['*']
            allow_methods: ['*']
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
            forced_allow_origin_value: ~
        paths:
            '^/api/':
                origin_regex: true
                allow_origin: ['^https?://.*?$','^http?://.*?$','https://ricbe.herokuapp.com/','http://ricbe.herokuapp.com/','^http://localhost:[0-9]+']
                allow_headers: ['*','access-control-allow-origin']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
            '^/':
                origin_regex: true
                allow_origin: ['^http://localhost:[0-9]+','https://ricbe.herokuapp.com/','http://ricbe.herokuapp.com/','^https?://.*?$','^http?://.*?$']
                allow_headers: ['*','access-control-allow-origin']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
                hosts: ['^api\.']
